variables:
  DOCKER_DRIVER: overlay2

stages:
- build

before_script:
    - rm -fr build SOURCES RPMS

.centoscommon: &centoscommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/\(.\)%{?dist}/\1.b$CI_PIPELINE_ID%{?dist}/g" redhat/freeradius.spec
    - "wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2Ftrust_router/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip"
    - yum -y install RPMS/x86_64/trust_router-devel*.rpm RPMS/x86_64/trust_router-libs*.rpm RPMS/x86_64/trust_router-debuginfo*.rpm
    - rm -fr RPMS SRPMS deps.zip
    - ./configure
    - make dist
    - mkdir SOURCES
    - cp freeradius*.tar.bz2 SOURCES
    - cp redhat/* SOURCES
    - rpmbuild -ba redhat/freeradius.spec --define "_topdir `pwd`"
  artifacts:
    expire_in: 6 months
    paths:
        - RPMS
        - SRPMS

.debiancommon: &debiancommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/DIST/$CI_JOB_NAME.$CI_PIPELINE_ID/g" debian/changelog
    - "wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2Ftrust_router/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip"
    - "dpkg -i build/moonshot-trust-router-dev*.deb build/libtr-tid2*.deb"
    - echo "rlm_python3" >> src/modules/stable
    - fakeroot debian/rules debian/control
    - debuild -us -uc
    - rm -fr build deps.zip
    - mkdir build
    - cp ../*.deb ../*.dsc ../*tar* build
  artifacts:
    expire_in: 6 months
    paths:
        - build/*

.alpinecommon: &alpinecommon
  stage: build
  except:
    - tags
  tags:
    - moonshot
  script:
    - sed -i "s/pkgrel=.*/pkgrel=$CI_PIPELINE_ID/g" alpine/APKBUILD
    - "wget --header \"PRIVATE-TOKEN: $TOKEN\" https://gitlab.ci.ti.ja.net/api/v4/projects/moonshot%2Ftrust_router/jobs/artifacts/develop/download?job=$CI_JOB_NAME -O deps.zip; unzip deps.zip"
    - apk add apks/*/*.apk --allow-untrusted
    - rm -fr apks deps.zip
    - adduser -D tmpuser -s /bin/sh
    - adduser tmpuser abuild
    - ./configure
    - make dist
    - cp freeradius-server-*.tar.gz alpine
    - cd alpine
    - sudo -u tmpuser abuild checksum
    - sudo -u tmpuser abuild-keygen -an
    - sudo -u tmpuser abuild -r
    - cd ..
    - mkdir apks
    - mv /home/tmpuser/packages/*/* apks
  artifacts:
    expire_in: 6 months
    paths:
        - apks/*/*.apk

centos6:
  image: $DOCKER_REGISTRY_URL/centos6:latest
  <<: *centoscommon

centos7:
  image: $DOCKER_REGISTRY_URL/centos7:latest
  <<: *centoscommon

centos8:
  image: $DOCKER_REGISTRY_URL/centos8:latest
  <<: *centoscommon

debian8:
  image: $DOCKER_REGISTRY_URL/debian8:latest
  <<: *debiancommon

debian9:
  image: $DOCKER_REGISTRY_URL/debian9:latest
  <<: *debiancommon

debian10:
  image: $DOCKER_REGISTRY_URL/debian10:latest
  <<: *debiancommon

raspbian8:
  when: manual
  image: $DOCKER_REGISTRY_URL/raspbian8:latest
  <<: *debiancommon

raspbian9:
  when: manual
  image: $DOCKER_REGISTRY_URL/raspbian9:latest
  <<: *debiancommon

raspbian10:
  when: manual
  image: $DOCKER_REGISTRY_URL/raspbian10:latest
  <<: *debiancommon

ubuntu16:
  image: $DOCKER_REGISTRY_URL/ubuntu16:latest
  <<: *debiancommon

ubuntu18:
  image: $DOCKER_REGISTRY_URL/ubuntu18:latest
  <<: *debiancommon

ubuntu20:
  image: $DOCKER_REGISTRY_URL/ubuntu20:latest
  <<: *debiancommon

alpine39:
  image: $DOCKER_REGISTRY_URL/alpine39:latest
  <<: *alpinecommon

alpine39_armhf:
  when: manual
  image: $DOCKER_REGISTRY_URL/alpine39_arm:latest
  <<: *alpinecommon

alpine311:
  image: $DOCKER_REGISTRY_URL/alpine311:latest
  <<: *alpinecommon

alpine311_armhf:
  when: manual
  image: $DOCKER_REGISTRY_URL/alpine311_arm:latest
  <<: *alpinecommon
