#! /bin/sh

set -e

case "$1" in
  configure)
        if [ -x "`which invoke-rc.d 2>/dev/null`" ]; then
          # Customized by Painless Security: Don't abort install if the reload fails
          invoke-rc.d freeradius force-reload || true
        else
          # Customized by Painless Security: Don't abort install if the reload fails
          /etc/init.d/freeradius force-reload || true
        fi
	;;
esac

#DEBHELPER#

exit 0


